### ISSUE TITLE
How to output aleatoric and epistemic uncertainties associated to the class

### ISSUE THREAD

**Issue by BrenoAV** [NVlabs/AL-MDN#10]
Greetings,

I was trying to print out the uncertainties just the way it is shown in Figure 3 from the paper:

![uncertainties](https://user-images.githubusercontent.com/58391216/159499264-39a940f4-daa6-473b-8739-767fd732281f.png)

Where should I tweak the code, so that I can output those 4 uncertainty values for each image?

In /layers/functions/detection_gmm.py there's one output variable with should contain uncertainties, but I wasn't able to understand the output. Is there anything I'm missing/misunderstanding?

**Comment by jwchoi384** [comment]
Hello @BrenoAV 
As you can see [this line](https://github.com/NVlabs/AL-MDN/blob/54aaae4405c69b33998e5b5306c7c645780d473c/layers/functions/detection_gmm.py#L109), output contains scores, box coordinates, aleatoric & epistemic uncertainties of each task.
You can print out each uncertainty value using [`detections` variable](https://github.com/NVlabs/AL-MDN/blob/54aaae4405c69b33998e5b5306c7c645780d473c/demo.py#L81), like [scores](https://github.com/NVlabs/AL-MDN/blob/54aaae4405c69b33998e5b5306c7c645780d473c/demo.py#L87) and [box coordinates](https://github.com/NVlabs/AL-MDN/blob/54aaae4405c69b33998e5b5306c7c645780d473c/demo.py#L93).
To output normalized values, you need to know the mean and variance of each uncertainty distribution for the dataset.
For doing this, you can use [this function](https://github.com/NVlabs/AL-MDN/blob/54aaae4405c69b33998e5b5306c7c645780d473c/active_learning_loop.py#L259).

**Comment by BrenoAV** [comment]
It makes sense now for me, thank you very much @jwchoi384

**Comment by abwgmo** [comment]
hello please if you have a concrete example how to recover them for each image?
@jwchoi384 @BrenoAV

**Comment by BrenoAV** [comment]
What I do understand, please correct me if I'm wrong.

You can take these values from here [layers/functions/detection_gmm.py](https://github.com/NVlabs/AL-MDN/blob/54aaae4405c69b33998e5b5306c7c645780d473c/layers/functions/detection_gmm.py#L109-L119):

![uc1](https://user-images.githubusercontent.com/58391216/187768169-a2d35d56-dbdb-4da7-86aa-bb8885017d42.png)

For example, in the demo.py file... When you test some image you can use the [while loop](https://github.com/NVlabs/AL-MDN/blob/54aaae4405c69b33998e5b5306c7c645780d473c/demo.py#L86) to obtain the uncertainty for each bbox, something like this:

```python
max_loc_al_uc = torch.max(detections[0][i][j][5:9]) # 4 values (four coordinates values)
max_loc_ep_uc = torch.max(detections[0][i][j][9:13]) # 4 values (four coordinates values)
cl_al_uc = torch.max(detections[0][i][j][13:14]) # 1 value
cl_ep_uc = torch.max(detections[0][i][j][14:15]) # 1 value
```

**Comment by abwgmo** [comment]
Thank you @BrenoAV  very much for your answer indeed the same thing that I understood but I have a small concern concerning the four values ​​for the random and epistimological localisation why it sends 4 values ​​instead of a single value as the case of the classification. and for the [function](https://github.com/NVlabs/AL-MDN/blob/54aaae4405c69b33998e5b5306c7c645780d473c/active_learning_loop.py#L259)  can we use it if we want to select a set of images to label ?

**Comment by BrenoAV** [comment]
For the localization, the 4 values are the uncertainty about the center, height, and weight {x, y, w, h}. On pg. 4 of the paper in section 3.3 Scoring Function: "[...] For localization, $u^{ij}$ is the maximum value over the 4 bounding box outputs. [...]"

And in the function you cited, you want to take the [labeled_set](https://github.com/NVlabs/AL-MDN/blob/54aaae4405c69b33998e5b5306c7c645780d473c/active_learning_loop.py#L325) because they have high score values, labeling them and continue the active learning loop.

**Comment by abwgmo** [comment]
thank you once again @BrenoAV  for your help and support now things seem understandable.
