### ISSUE TITLE
How to use GMM in Faster RCNN?

### ISSUE THREAD

**Issue by ChuQiaosong** [NVlabs/AL-MDN#11]
Thanks for your great work! As you have mentioned in your paper, GMM works well on Faster RCNN. So can you share your code on Faster RCNN? I want to do some experiments on a two-stage detector.

**Comment by jwchoi384** [comment]
Hi @ChuQiaosong, Sorry for the late reply.
I do not currently have the implemented Faster RCNN code. However, the implementation is quite simple.
You can set additional heads in the output layer of the Faster RCNN and implement the proposed loss functions on Faster RCNN's loss part by referring to this repo.
