### ISSUE TITLE
The question of the mixture weight π of GMM

### ISSUE THREAD

**Issue by hantaotao** [NVlabs/AL-MDN#3]
We have trained a model with this method on our dataset. In the test phase, We find that the π value in the one of four classification components of GMM is close to 1, and  the rest of π values are too small (close to 0), is this correct? Do you have similar situations? If not, what’s the π value of the four classification components when testing? Looking forward to your reply, thanks!

**Comment by jwchoi384** [comment]
Hello,
Please try setting `cls_type='Type-1'` to `cls_type='Type-2'`.
https://github.com/NVlabs/AL-MDN/blob/54aaae4405c69b33998e5b5306c7c645780d473c/layers/modules/multibox_loss_gmm.py#L49

This is referred to in Section D of our supplementary material. Please see the link below.
https://openaccess.thecvf.com/content/ICCV2021/supplemental/Choi_Active_Learning_for_ICCV_2021_supplemental.pdf

**Comment by hantaotao** [comment]
Thank you for your reply! 
We have read this section. From our point of view, the main difference between Eq. 5 and Eq.1 lies in the order of mixture weight π: 
∑-π*log(softmax(c))  (Eq.5)
-log(∑π*softmax(c))  (Eq.1 in Supp)
But we can’t understand why Eq.5 make the mixture weight π concentrate in one of the distribution, while Eq.1 can alleviate this trend. Could you please explain it? Thanks!

**Comment by jwchoi384** [comment]
I haven't found the exact cause of the bias.
I have experimentally checked that the classification loss of the supplementary material alleviates the bias.
If your dataset has a small number of classes, I would recommend using the classification loss of Supp.
