### ISSUE TITLE
Question of AL selecting the best weight 

### ISSUE THREAD

**Issue by yisyuanliou** [NVlabs/AL-MDN#5]
Hi, I have some questions about the code in  https://github.com/NVlabs/AL-MDN/blob/main/train_ssd_gmm_active_learining.py#L292-L318
In the active learning stage, why only select the best weight for the PASCAL VOC dataset but not for the COCO dataset?
Thanks!

**Comment by tsunghan-wu** [comment]
Face the same issue and would like to know why +1.

**Comment by jwchoi384** [comment]
Hello @yisyuanliou, @tsunghan-mama,
In our experiments, for PASCAL VOC, the accuracy was sometimes better at iterations smaller than the maximum iterations (i.e., 120000). However, for COCO, it had the best accuracy at maximum iterations.
This is why we selected the best weight only in PASCAL VOC.
