### ISSUE TITLE
About Eq.5 

### ISSUE THREAD

**Issue by zyg519** [NVlabs/AL-MDN#9]
![image](https://user-images.githubusercontent.com/56619139/158502066-ffcd796f-1311-4d4f-934f-1d6889488190.png)

Very sorry for disturbing you， I would like to ask why there is an add operation？

**Comment by jwchoi384** [comment]
That part is from `LogSoftmax`. Please see this [link](https://pytorch.org/docs/stable/generated/torch.nn.LogSoftmax.html#torch.nn.LogSoftmax).
